= Universal Declaration of Human Rights
:date: 2021-09-20
:copyright: © The Office of the High Commissioner for Human Rights 1996–2009
:description: Universal Declaration of Human Rights
:author: The Office of the High Commissioner for Human Rights
:keywords: "Human rights", "United Nations", udhr
:sectnumlevels: 0
:lang: en
:page-lang: {lang}
:page-image: udhr.svg

{copyright}

[abstract]
== Preamble

image::en@i18n-v2:ROOT:udhr.svg[Universal Declaration of Human Rights,356,480,float="left"]

鉴于承认人类大家庭所有成员的固有尊严以及平等和不可剥夺的权利是世界自由、正义与和平的基础，

鉴于对人权的无视和蔑视导致了触怒人类良知的野蛮行径，一个人类享有言论和信仰自由以及免于恐惧和匮乏的世界的到来被宣布为最高愿望普通人中，

鉴于如果人类不想被迫求助于反抗暴政和压迫作为最后的手段，那么人权就必须受到法治的保护，

鉴于促进国家间友好关系的发展至关重要，

鉴于联合国人民在《宪章》中重申了他们对基本人权、人格尊严和价值以及男女平等权利的信念，并决心促进社会进步和提高生活水平更大的自由度，

鉴于会员国承诺与联合国合作，促进普遍尊重和遵守人权和基本自由，

鉴于对这些权利和自由的共同理解对于充分实现这一承诺至关重要，因此，大会现在宣布本《世界人权宣言》作为所有人民和所有国家实现目标的共同标准，每个人和社会的每个机构都应牢记本宣言，努力通过教学和教育促进对这些权利和自由的尊重，并通过国家和国际的渐进措施确保这些权利和自由得到普遍和有效的承认和遵守，无论是在成员国人民本身还是在其管辖下的领土人民之间。

== 第一条

人人生而自由，在尊严和权利上一律平等。
他们被赋予了理性和良知，应该本着手足情谊的精神对待彼此。

== 第 2 条

人人有权享有本宣言所载的所有权利和自由，不分种族、肤色、性别、语言、宗教、政治或其他见解、国籍或社会出身、财产、出生或其他身份等任何区别。

此外，不得因个人所属国家或领土的政治、管辖或国际地位而有所区别，无论该国家或领土是独立的、托管的、非自治的还是处于任何其他主权限制之下。

== 第三条

人人享有生命权、自由权和人身安全权。

== 第 4 条

任何人不得被奴役或奴役；禁止一切形式的奴隶制和奴隶贸易。

== 第五条

任何人不得遭受酷刑或残忍、不人道或有辱人格的待遇或处罚。

== 第六条

每个人都有权在任何地方获得法律面前人格的承认。

== 第七条

法律面前人人平等，并有权不受任何歧视地受到法律的平等保护。
所有人都有权获得平等保护，免受任何违反本宣言的歧视和任何煽动此类歧视的行为。

== 第八条

对于侵犯宪法或法律授予他的基本权利的行为，每个人都有权获得主管国家法庭的有效补救。

== 第九条

任何人不得被任意逮捕、拘留或流放。

== 第十条

每个人都完全平等地有权由一个独立和公正的法庭进行公平和公开的审理，以确定他的权利和义务以及对他的任何刑事指控。

== 第十一条

.任何被控犯有刑事罪的人都有权被推定为无罪，直到在公开审判中依法证明他有罪，而他在公开审判中获得了辩护所必需的一切保障。
.任何人不得因在犯罪时根据国家或国际法不构成刑事犯罪的任何作为或不作为而被判有罪。
.也不得施加比犯罪时适用的刑罚更重的刑罚。

== 第十二条

任何人的隐私、家庭、住宅或通信不得任意干涉，其荣誉和名誉不得受到攻击。
每个人都有权受到法律保护，免受此类干涉或攻击。

==第13条

.每个人都有权在每个国家的边界​​内自由迁徙和居住。
.每个人都有权离开任何国家，包括他自己的国家，并有权返回他的国家。

== 第十四条

.每个人都有权在其他国家寻求和享受庇护以免受迫害。
